name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  my_new_project:  # Make sure the project name matches here
    customers:
      +materialized: incremental
    employees:
      +materialized: incremental
    offices:
      +materialized: incremental
    orderdetails:
      +materialized: incremental
    orders:
      +materialized: incremental
    productlines:
      +materialized: incremental
    products:
      +materialized: incremental
