
version: 2
sources:
  - name: devstage  # Schema name
    tables:
      - name: offices
      - name: employees
      - name: customers
      - name: payments
      - name: orderdetails
      - name: orders
      - name: productlines
      - name: products
      

  - name: devdw  # Schema name
    tables:
      - name: offices
      - name: employees
      - name: customers
      - name: payments
      - name: orderdetails
      - name: orders
      - name: productlines
      - name: products
      - name: employees_history
      - name: customer_history
      - name: product_history
      - name: monthly_customer_summary
      - name: monthly_product_summary
      - name: daily_product_summary
    
  - name: metadata # Schema name
    tables:
      - name: batch_control
